POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testing async title",
    "author": "Testing async author",
    "url": "http://www.testingloggerurl.com",
    "likes": 4
}