POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testing final ref logger 2 title",
    "author": "Testing final ref logger 2 author",
    "url": "http://www.testingloggerurl.com",
    "likes": 9
}