POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testing morgan title",
    "author": "Testing morgan author",
    "url": "http://www.testingloggerurl.com",
    "likes": 8
}